In [3]:
import numpy as np
a = np.array([1, 2, 6, 4, 2, 3, 2])
u, indices_a = np.unique(a, return_inverse=True)
u


array([1, 2, 3, 4, 6])

In [4]:
indices_a #these indices point at locations in the UNIQUE MATRIX(!) and can be used to restore original matrix

array([0, 1, 4, 3, 1, 2, 1], dtype=int64)

In [59]:
u[indices_a] 

array([1, 2, 6, 4, 2, 3, 2])

In [15]:
u, indices_b = np.unique(a, return_index=True)

In [16]:
indices_b #these indexes point at values in the ORIGINAL MATRIX (!) that form the unique matrix

array([0, 1, 5, 3, 2], dtype=int64)

In [57]:
A = np.array([1,-1,-3,4,-5])

A[indices_a]

array([ 1, -1, -5,  4, -1, -3, -1])

In [5]:
# empty list
print(list())

# vowel string
vowelString = 'aeiou'
print(list(vowelString))

# vowel tuple
vowelTuple = ('a', 'e', 'i', 'o', 'u')
print(list(vowelTuple))

# vowel list
vowelList = ['a', 'e', 'i', 'o', 'u']
print(list(vowelList))

[]
['a', 'e', 'i', 'o', 'u']
['a', 'e', 'i', 'o', 'u']
['a', 'e', 'i', 'o', 'u']


In [55]:
# vowel set
vowelSet = {'a', 'e', 'i', 'o', 'u'} #??????????????????????????????????? wtf
print(list(vowelSet))

# vowel dictionary
vowelDictionary = {'a': 1, 'e': 2, 'i': 3, 'o':4, 'u':5}
print(list(vowelDictionary))

['3', '1', '2']
['a', 'e', 'i', 'o', 'u']


In [8]:
class PowTwo:
    def __init__(self, max):
        self.max = max
    
    def __iter__(self):
        self.num = 0
        return self
        
    def __next__(self):
        if(self.num >= self.max):
            raise StopIteration
        result = 2 ** self.num
        self.num += 1
        return result

powTwo = PowTwo(5)
powTwoIter = iter(powTwo)

print(list(powTwoIter))

[1, 2, 4, 8, 16]


In [9]:
my_list = ['p','r','o','g','r','a','m','i','z']
# elements 3rd to 5th
print(my_list[2:5])
# elements beginning to 4th
print(my_list[:-5])
# elements 6th to end
print(my_list[5:])
# elements beginning to end
print(my_list[:])

['o', 'g', 'r']
['p', 'r', 'o', 'g']
['a', 'm', 'i', 'z']
['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']


In [12]:
# mistake values
odd = [2, 4, 6, 8]
# change the 1st item    
odd[0] = 1            
# Output: [1, 4, 6, 8]
print(odd)
# change 2nd to 4th items
odd[1:4] = [3, 5, 7]  
# Output: [1, 3, 5, 7]
print(odd)          

[1, 4, 6, 8]
[1, 3, 5, 7]


In [17]:
odd = [1, 9]
odd.insert(0,3)# insert(index,alue)
# Output: [1, 3, 9] 
print(odd)
odd[2:2] = [5, 7]
# Output: [1, 3, 5, 7, 9]
print(odd)


[3, 1, 9]
[3, 1, 5, 7, 9]


In [28]:
odd = [1, 9]
odd.insert(1,3)
# Output: [1, 3, 9] 
print(odd)
odd[2:2] = [5, 7] #2:2 to just insert between 3 and 9, but if 2:3, it erases 9 and replaces it with 7 and adding a 5
# Output: [1, 3, 5, 7, 9]
print(odd)

[1, 3, 9]
[1, 3, 5, 7, 9]


In [35]:
for fruit in ['apple','banana','mango']:
    print("I like",fruit)

I like apple
I like banana
I like mango


In [57]:
# empty list
print(list())

# vowel string
vowelString = 'aeiou'
print(list(vowelString))

# vowel tuple
vowelTuple = ('a', 'e', 'i', 'o', 'u')
print(list(vowelTuple))

# vowel list
vowelList = ['a', 'e', 'i', 'o', 'u']
print(list(vowelList))

[]
['a', 'e', 'i', 'o', 'u']
['a', 'e', 'i', 'o', 'u']
['a', 'e', 'i', 'o', 'u']
